### ISSUE TITLE
ln: failed to create symbolic link ‘/home/vagrant/.composer/cache’: Permission denied

### ISSUE THREAD

**Issue by raamdev** [websharks/ubuntu-bootstrap#12]
I'm not sure what's causing this, but when I tried starting my VM based on Ubuntu-Bootstrap, I get the following:

```
==> default: Configuring cache buckets...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ln -s /tmp/vagrant-cache/composer /home/vagrant/.composer/cache

Stdout from the command:



Stderr from the command:

ln: failed to create symbolic link ‘/home/vagrant/.composer/cache’: Permission denied
```

**Comment by raamdev** [comment]
This seems to have fixed the issue:

```
$ vagrant ssh
$ sudo chown -R vagrant:vagrant /home/vagrant/.composer/
$ exit
$ vagrant reload
```

**Comment by raamdev** [comment]
Ran into this again today. Any idea what might be causing it?

**Comment by jaswrks** [comment]
Hmm. I'm guessing this could be caused by Vagrant itself. Maybe there is a routine that does a reset of permissions in the `/home/vagrant` directory whenever you `vagrant up`. Is that what you're finding? i.e., the permissions on that directory are being changed automatically in some way?

I haven't seen this myself yet, but that might be because I don't generally operate as the `vagrant` user whenever I'm working at the command line on the VM. Nothing wrong with doing that though. I just got into the habit of using my own account instead, or I'll interact with the VM as root (more common).

``` bash
$ vagrant ssh
$ sudo -i -u admin # Your personal account.
# The default is `admin`, but you can change this in the bootstrap installer.
```

Or, just to become root, which is what I do most often.

``` bash
$ vagrant ssh
$ sudo -i
```

**Comment by jaswrks** [comment]
Note that you can also do this just like you would for any other box.

``` bash
$ ssh admin@my.vm
```

Password is `admin`.

**Comment by raamdev** [comment]
> Is that what you're finding? i.e., the permissions on that directory are being changed automatically in some way?

I'm not sure—I don't know what the permissions are in the first place and by the time this issue comes up it's too late to find out. :-) 

> that might be because I don't generally operate as the vagrant user whenever I'm working at the command line on the VM

I generally don't work on the command line in the VM at all—the only time I do is when I'm setting up the VM for the first time to run the installer. Once that's done and I have the system configured the way I want, the only thing I ever do with it is `vagrant up` and `vagrant halt`.

**Comment by jaswrks** [comment]
Well, it looks like this is related to the `vagrant-cachier` plugin, which I removed support for in the latest release of the WUBS because I had some problems with it also. So you're not alone.

``` bash
$ vagrant plugin uninstall vagrant-cachier
```

That might rid you of this issue.

**Comment by raamdev** [comment]
```
$ vagrant plugin uninstall vagrant-cachier
Uninstalling the 'vagrant-cachier' plugin...
```

Done. Hopefully I won't see this issue again! I'll close it for now and reopen if it happens again. Thanks!
